# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Upload Binary

on:
  push:
    tags:
      - "*"

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci

  upload:
    needs: sanity
    name: Publish for ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: Linux
            artifact_name: discord-bot
            platform: linux-x64
            file_suffix: linux-x64
          - os: Windows
            artifact_name: discord-bot.exe
            platform: win-x64
            file_suffix: win-x64.exe
          - os: MacOS
            artifact_name: discord-bot
            platform: macos-x64
            file_suffix: macos-x64

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        name: Get version
        id: get_version
      - run: npm ci
        name: Install dependencies
      - run: npm run pkg -- -t node12-${{ matrix.platform }}
        name: Pack the binary using vercel/pkg
      - run: file ./dist/*
        name: Check the binary
      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/${{ matrix.artifact_name }}
          asset_name: discord-bot-${{ steps.get_version.outputs.VERSION }}-${{ matrix.file_suffix }}
          tag: ${{ github.ref }}
